export const adoptionPosts = [
    {
        id: '1',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717431096/adopet/gkmiq11bgu1yuhdfgzh5.jpg',
        vet_category: 'Bird',
        vet_breed: 'Blue-parakeet',
        status: 'adopted',
        owner: 'Snehodipto Das',
    },
    {
        id: '2',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717431685/adopet/u8nehg6okahi5dxoekzb.jpg',
        vet_category: 'Rabbit',
        vet_breed: 'Holland-lop',
        status: 'available',
        owner: 'Snehodipto Das',
    },
    {
        id: '3',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717450074/adopet/g9kdzkh51ljhkfjbvkfr.jpg',
        vet_category: 'Dog',
        vet_breed: 'German shepherd',
        status: 'available',
        owner: 'Vikram Kumar',
    },
    {
        id: '4',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717593090/adopet/apmcdmse9mgl6bvukdk6.jpg',
        vet_category: 'Dog',
        vet_breed: 'Bulldog',
        status: 'adopted',
        owner: 'Renessa Chattoraj',
    },
    {
        id: '5',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717432827/adopet/wxd6ezfqswepo8eugygt.jpg',
        vet_category: 'Turtle',
        vet_breed: 'Hawksbill',
        status: 'adopted',
        owner: 'Ajay Singh',
    },
    {
        id: '6',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1720083575/adopet/wxtc7arib3wgczrb3o6v.png',
        vet_category: 'Snake',
        vet_breed: 'Swamp-adder',
        status: 'available',
        owner: 'Snehodipto Das',
    },
]

export const rescuePosts = [
    {
        id: '1',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717431096/adopet/gkmiq11bgu1yuhdfgzh5.jpg',
        vet_category: 'Bird',
        health_status: ['Injured', 'Needs medical care'],
        status: 'rescued',
        owner: 'Snehodipto Das',
    },
    {
        id: '2',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717431685/adopet/u8nehg6okahi5dxoekzb.jpg',
        vet_category: 'Rabbit',
        health_status: ['Injured'],
        status: 'rescued',
        owner: 'Snehodipto Das',
    },
    {
        id: '3',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717450074/adopet/g9kdzkh51ljhkfjbvkfr.jpg',
        vet_category: 'Dog',
        health_status: ['Injured'],
        status: 'pending',
        owner: 'Vikram Kumar',
    },
    {
        id: '4',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717593090/adopet/apmcdmse9mgl6bvukdk6.jpg',
        vet_category: 'Dog',
        health_status: ['Injured'],
        status: 'pending',
        owner: 'Renessa Chattoraj',
    },
    {
        id: '5',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717432827/adopet/wxd6ezfqswepo8eugygt.jpg',
        vet_category: 'Turtle',
        health_status: ['Needs Medical care'],
        status: 'rescued',
        owner: 'Ajay Singh',
    },
    {
        id: '6',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1720083575/adopet/wxtc7arib3wgczrb3o6v.png',
        vet_category: 'Snake',
        health_status: ['Injured'],
        status: 'pending',
        owner: 'Snehodipto Das',
    },
]

export const adoptionPostsRecent = [
    {
        id: '1',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717431096/adopet/gkmiq11bgu1yuhdfgzh5.jpg',
        vet_category: 'Bird',
        vet_breed: 'Blue-parakeet',
        status: 'adopted',
        owner: 'Snehodipto Das',
    },
    {
        id: '2',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717431685/adopet/u8nehg6okahi5dxoekzb.jpg',
        vet_category: 'Rabbit',
        vet_breed: 'Holland-lop',
        status: 'available',
        owner: 'Snehodipto Das',
    },
    {
        id: '3',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717450074/adopet/g9kdzkh51ljhkfjbvkfr.jpg',
        vet_category: 'Dog',
        vet_breed: 'German shepherd',
        status: 'available',
        owner: 'Vikram Kumar',
    },
    {
        id: '4',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717593090/adopet/apmcdmse9mgl6bvukdk6.jpg',
        vet_category: 'Dog',
        vet_breed: 'Bulldog',
        status: 'adopted',
        owner: 'Renessa Chattoraj',

    },
    {
        id: '5',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717432827/adopet/wxd6ezfqswepo8eugygt.jpg',
        vet_category: 'Turtle',
        vet_breed: 'Hawksbill',
        status: 'adopted',
        owner: 'Ajay Singh',
    },
    {
        id: '6',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1720083575/adopet/wxtc7arib3wgczrb3o6v.png',
        vet_category: 'Snake',
        vet_breed: 'Swamp-adder',
        status: 'available',
        owner: 'Snehodipto Das',
    },
    {
        id: '7',
        vet_image: "https://res.cloudinary.com/dtfoedy3u/image/upload/v1720162442/m7sizz0fe4xt2xesbbzq.jpg",
        vet_category: 'Chameleon',
        vet_breed: 'Holland-lop',
        status: 'available',
        owner: 'Vikram Kumar',
    },
    {
        id: '8',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717593090/adopet/apmcdmse9mgl6bvukdk6.jpg',
        vet_category: 'Dog',
        vet_breed: 'Labrador',
        status: 'adopted',
        owner: 'Ajay Singh',

    },
    {
        id: '9',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717432827/adopet/wxd6ezfqswepo8eugygt.jpg',
        vet_category: 'Fish',
        vet_breed: 'Goldfish',
        status: 'adopted',
        owner: 'Renessa Chattoraj',
    },
    {
        id: '10',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1720083575/adopet/wxtc7arib3wgczrb3o6v.png',
        vet_category: 'Snake',
        vet_breed: 'Russell-vipers',
        status: 'available',
        owner: 'Snehodipto Das',
    },
]

export const rescuePostsRecent = [
    {
        id: '1',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717431096/adopet/gkmiq11bgu1yuhdfgzh5.jpg',
        vet_category: 'Bird',
        health_status: ['', 'Critically injured'],
        rescue_date: '23/04/24',
    },
    {
        id: '2',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717431685/adopet/u8nehg6okahi5dxoekzb.jpg',
        vet_category: 'Rabbit',
        health_status: ['', 'Injured'],
        rescue_date: '11/01/24',
    },
    {
        id: '3',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717450074/adopet/g9kdzkh51ljhkfjbvkfr.jpg',
        vet_category: 'Dog',
        health_status: ['', 'Critically injured'],
        rescue_date: '19/02/24',
    },
    {
        id: '4',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717593090/adopet/apmcdmse9mgl6bvukdk6.jpg',
        vet_category: 'Dog',
        health_status: ['', 'Medical attention needed'],
        rescue_date: '24/02/24',
    },
    {
        id: '5',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717432827/adopet/wxd6ezfqswepo8eugygt.jpg',
        vet_category: 'Turtle',
        health_status: ['', 'Injured'],
        rescue_date: '04/06/24',
    },
    {
        id: '6',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1720083575/adopet/wxtc7arib3wgczrb3o6v.png',
        vet_category: 'Snake',
        health_status: ['', 'Injured'],
        rescue_date: '14/06/24',
    },
    {
        id: '7',
        vet_image: "https://res.cloudinary.com/dtfoedy3u/image/upload/v1720162442/m7sizz0fe4xt2xesbbzq.jpg",
        vet_category: 'Chameleon',
        health_status: ['', 'Injured'],
        rescue_date: '19/02/24',
    },
    {
        id: '8',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717593090/adopet/apmcdmse9mgl6bvukdk6.jpg',
        vet_category: 'Dog',
        health_status: ['', 'Critically Injured'],
        rescue_date: '09/06/24',
    },
    {
        id: '9',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1717432827/adopet/wxd6ezfqswepo8eugygt.jpg',
        vet_category: 'Fish',
        health_status: ['', 'Medical attention needed'],
        rescue_date: '28/02/24',
    },
    {
        id: '10',
        vet_image: 'https://res.cloudinary.com/dkf5lwjqr/image/upload/v1720083575/adopet/wxtc7arib3wgczrb3o6v.png',
        vet_category: 'Snake',
        health_status: ['', 'Injured'],
        rescue_date: '31/01/24',
    },
]